version: "3.8"

services:
  frontend:
    build: .
    container_name: vite-frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
